### ISSUE TITLE
Preserve style input

### ISSUE THREAD

**Issue by Rapster** [yuanqing/autosize-input#7] opened 2016-12-12 17:12 UTC
It would be nice to keep defined style:

```html
<input type="text" id="baz" placeholder="Matter" style="max-width: 200px">
```

Resize is nice, but don't resize too much though :p

**Comment by yuanqing** [comment] 2018-03-25 15:44
Closing because this seems to be a duplicate of #9

**Closed as completed by yuanqing** 2018-03-25 15:44 UTC
